// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntctmdwxyjnxconnsirk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50Y3RtZHd4eWpueGNvbm5zaXJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNzkxNTgsImV4cCI6MjA2NDk1NTE1OH0.7bfnL68_Ae0IUcmQG68QMtc5D71CMkVvzS1pwGGuu94";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);